#pragma once

#include "render.h"   // GuiRect, GuiColor, palette(), scaled_px

#include <cairo.h>

// THE CLEARLOOKS PAINTERS (architect 2026-10-07, the painters round's first
// part: the top strip; its second: the dialogs' push buttons and entries,
// the dropdown, the lists; its last: the trim lane as the scroll bar, the
// scrub as GtkScale, row 8's entry time fields, the well's frame, the
// ruler's ticks, the restored laptop's frame) — the chrome spec's clearlooks
// arm (chrome_spec.h; the flag editor is the program's own flag in its
// selected face under every chrome, render_flag_editor_box, architect
// 2026-10-07 ~09:45),
// GNOME 2.30's own drawing as Debian 6 squeeze put it on screen: the
// metacity theme's maximised caption (gnome-themes 2.30.2's Clearlooks
// metacity-theme-1.xml), and gtk-engines 2.20.2's Clearlooks GUMMY style for
// the menu bar, the toolbar band, its tool buttons and separators, the push
// button, the entry, the menu and its items, the list and its selected cell
// (clearlooks_draw.c, clearlooks_draw_gummy.c), the scroll bar and the scale
// (the same files), the restored window's frame (metacity's
// `normal` frame style set), his squeeze captures the law
// (tmp/squeeze/). Every painter here is called from its win2000 sibling's
// site on the spec's fork (paint_handler.cpp) and reads its lengths from the
// live spec, so a length changed at the instance moves the drawing with no
// edit here (and the tones with one re-run of tools/theme_catalog, which
// reads the same instance).
//
// FOUR RULES OF THE PALETTE HEAD BEND FOR THIS VOCABULARY ONLY (report CL1
// §4; render.h's palette head names this block as the bend's one statement),
// THE WIN2000 PAINTERS UNTOUCHED BY ALL FOUR:
//   1. EVERY COLOUR IS A ROLE STILL, generated by need: the `cl_` block of
//      the role table (theme_file.h, theme_clearlooks_roles.inc), each byte
//      the engine's own arithmetic run once at import (tools/theme_catalog
//      build.py's engine tones). These painters read no other role but
//      `ground` (the window's bg, the same surface in both vocabularies).
//      The relief quartet, the mitre and the paint_relief_* families are
//      Windows' and are never read here (CL1 §4.5).
//   2. RAMPS BETWEEN RECORDED STOPS (CL1 §4.1; the planner's decision): the
//      engine's and metacity's vertical gradients, each painted by
//      paint_cl_ramp below — THE ONE INTERPOLATION RULE, the caption
//      gradient's own (paint_caption_gradient) turned vertical: device row i
//      of n takes round(s + (e − s)·i/(n − 1)) per channel, s and e the
//      segment's two stop roles, which are THE FIRST AND LAST ROWS THE
//      PERIOD PAINTED (the import's record), so at 1 W px the ends are the
//      captures' pixels and every row between lands within one level of the
//      period's (build.py asserts it). A one-row line is a fill.
//   3. ALPHA IS BAKED AT IMPORT, NEVER AT PAINT TIME (CL1 §4.3): where the
//      engine strokes a translucent colour over a known fill — the gummy
//      button's 0.4 top-left highlight, the pressed button's 0.58 -> 0 inner
//      shadow — the import composites it over that fill's recorded row and
//      records the result as a role (per row, or per column as a ramp's
//      ends); every byte painted here is opaque. ANTIALIASED EDGES ARE THE
//      RENDERER'S, as everywhere (the rounded corners' arcs, the Close
//      glyph's diagonals, the inset's diagonal split).
//   4. ROUNDED CORNERS (CL1 §4.2): the gummy boxes' corners are the spec's
//      corner_radius_px (the gtkrc's `radius = 3.0`), scaled like any length
//      and drawn as antialiased cairo arcs; win2000's radius is 0.
// AND ONE HOVER FACE MORE IS NOT ADDED (CL1 §4.6): the toolbar's HOT case
// (GTK's prelight) stays the one hover face; the menu bar's prelit title and
// the caption buttons' prelight are not drawn (metacity's button_bg_prelight
// and GTK's prelit menu title would be two new hover faces).
//
// THE GEOMETRY MAPS AT THE ELEMENT (render.h's scaled_px rule): an authored
// W-px coordinate k of a box at device origin o stands at o + scaled_px(k),
// every edge rounded on its own, so the box's parts tile it exactly; the
// gummy button's one-W lines are relief_line_px() wide, as every one-W line
// in the chrome.

// THE ONE RAMP RULE (rule 2 above): `r` filled top to bottom, device row i
// of r.h in round(top + (bottom − top)·i/(r.h − 1)) per channel (std::
// nearbyint, the tree's one rounding), each row one opaque cell rect, so a
// clip cuts it like any fill. The levels are sRGB, the period's own; each
// row is an authored color handed to paint_cell_rect and so converted for
// the window at the painter's entry (display_transform.h's head), the ramp
// never run between converted ends. Cannot fail.
void paint_cl_ramp(cairo_t* cr, const GuiRect& r, GuiColor top,
                   GuiColor bottom);
// THE SAME RAMP TURNED (2026-10-08, the popup lists' vertical scroll bar,
// whose drawing is the trim lane's with the axes exchanged): `r` filled left
// to right, device column i of r.w in round(left + (right − left)·i/(r.w − 1))
// per channel, each column one opaque cell rect — rule 2 across instead of
// down, nothing else changed.
void paint_cl_ramp_across(cairo_t* cr, const GuiRect& r, GuiColor left,
                          GuiColor right);

// THE CAPTION'S BAND — metacity's `bevel_maximized` (focused, shades of
// bg[SELECTED]) or `bevel_maximized_unfocused` (shades of bg[NORMAL]) on the
// lane `lane` (render.h's caption block): ROW 0 the 0.55 edge; UNFOCUSED,
// ROW 1 the 1.05 light line (focused, the upper gradient covers its 1.18
// line, as his captures show); the UPPER gradient down to row H/2 − 1, the
// LOWER from H/2 to H − 2 (covering the 0.94 / 0.89 line at H − 2); ROW
// H − 1 the 0.7 / 0.65 foot — H the spec's caption_height_px, the band's
// rows proportional to it (metacity's own top_height / 2 arithmetic).
void paint_cl_caption_band(cairo_t* cr, const GuiRect& lane, bool focused);

// The caption buttons' glyph (metacity's *_button_icon draw_ops).
enum class ClCaptionGlyph { Minimize, Maximize, Restore, Close };

// ONE CAPTION BUTTON on its box `b` (caption_button_rects, its W size the
// spec's caption_button_w_px x caption_button_h_px): metacity's button_bg
// (focused) / button_bg_unfocused, or their _pressed sets while `pressed`,
// DRAWN AS THE CONCENTRIC ANTIALIASED RINGS ITS STAIRCASE OF LINES STEPS
// ALONG (architect 2026-10-07, his glass verdict on the cell rects: "the
// caption buttons' boxes are pixelated"; the head's rule 4) — the halo, the
// border and the inner bevel about the point four W in, round the fill's
// gradients, each line's tone a role and each gradient a ramp between two,
// a ring's tones meeting on radial seams where the ops end its runs (the
// bevel's at 45 degrees, architect 2026-10-07: clearlooks_paint.cpp's
// caption-button block, where the radius and the seams are derived) — then
// the glyph at its icon_size, centred: the capture's proportion of the box
// under the fit, 6, for Close and Minimise (Minimise at 6 2026-10-07
// ~05:30: "it's supposed to signify being tiny"); metacity's Bmin 7 for
// Maximise and Restore, whose ops lose their window below it (architect
// 2026-10-07; caption_icon_size) — focused, the 0.7 outline under the
// blend(sel, white, 0.75) shape; unfocused, the blend(fg, bg, 0.45) shape
// alone. CLOSE'S
// CROSS is one antialiased path per tone — the width-2 diagonals from pixel
// centre to pixel centre, butt-capped, over the width-4 outline run one W
// past each end (the theme's end <tint>s, retired as cells:
// clearlooks_paint.cpp's glyph_cross and its Close case, architect
// 2026-10-07) — the scalable form of X's wide lines; every other glyph part
// is a cell rect, a one-px <line> X's own (its last point not drawn,
// glyph_hline). NO PUSH: metacity draws the pressed glyph in place. A
// DISABLED BUTTON (the tablet's Restore, which cannot restore: metacity
// draws no disabled button, it hides one) keeps its box and wears
// the unfocused glyph — the window manager's own "not yours now" ink (the
// planner's reading, 2026-10-07).
void paint_cl_caption_button(cairo_t* cr, const GuiRect& b,
                             ClCaptionGlyph glyph, bool focused, bool pressed,
                             bool enabled);

// THE MENU BAR'S GROUND — clearlooks_draw_menubar2 (menubarstyle 2) on the
// lane: the bg -> bg x 0.96 ramp down every row but the last, and the last
// row shade[3], the line between the menu bar and the toolbar.
void paint_cl_menubar(cairo_t* cr, const GuiRect& lane);

// THE OPEN MENU TITLE — clearlooks_gummy_draw_menubaritem on the anchor
// whose dropdown is down: x and width the anchor's, its rows the content's
// plus one (the style passes height + 1, so its foot is the bar's shade[3]
// row), the TOP corners rounded at the spec's radius: spot[1]'s gummy ramp
// (1.08 | 1.02 / 1.0 | 0.94) inside a one-W spot[2] border. The label over
// it is the caller's, in cl_menubaritem_text, unpushed.
void paint_cl_menubar_item(cairo_t* cr, const GuiRect& lane, int x, int w);

// THE TOOLBAR BAND — clearlooks_gummy_draw_toolbar (toolbarstyle 1, not
// topmost: it stands under the menu bar) on `band`, the icon row's band
// (row 8 is Nautilus's status bar, the ground alone — paint_bottom_strip):
// its first row bg x 1.1, the 1.04 | 1.01 / 1.0 | 0.97
// ramp with its step at the band's middle, its last row shade[3].
void paint_cl_toolbar_band(cairo_t* cr, const GuiRect& band);

// THE GROUP GAP'S SEPARATOR — clearlooks_gummy_draw_separator, vertical, in
// the gap starting at `gap_x` over the case [case_y, case_y + case_h): a
// shade[3] column at the spec's toolbar_separator_x_px and its 1.3 column
// beside it, inset toolbar_separator_inset_y_px at each end
// (_gtk_toolbar_paint_space_line's 20 % to 80 %).
void paint_cl_toolbar_separator(cairo_t* cr, int gap_x, int case_y,
                                int case_h);

// ONE TOOL BUTTON — GtkReliefNone in a toolbar (chrome_spec.h's
// GtkReliefNone), clearlooks_gummy_draw_button on the button style
// (xthickness 3, reliefstyle 1) where GTK paints a box at all:
//   REST     — nothing: the glyph on the band.
//   HOT      — the prelit button (bg[PRELIGHT], 1.06): the two shadow rings
//              of the parent's bg (0.97, 0.93), the gummy ramp, the border
//              mix (shade[6], fill, 0.2), the baked 0.4 top-left highlight.
//   PRESSED / CHECKED — the active button (bg[ACTIVE], 0.85): the parent's
//              inset ring (0.94 top-left / 1.06 bottom-right, split on the
//              diagonal), the ramp, the baked inner shadow over its first
//              three rows and columns, the border; the glyph one W px right
//              and down (GtkButton::child-displacement 1).
//   HOT AND CHECKED — GTK's prelit active toggle: the active button in
//              bg[PRELIGHT].
//   PRESSED AND CHECKED — the active button it already wears, the prelight
//              gone (2026-10-07 evening, the view group's lit radio arming):
//              GTK 2.20's gtk_toggle_button_update_state sets PRELIGHT only
//              while the button is not held down (no indicator drawn) and
//              the held toggle ACTIVE and depressed, so the press reads as
//              the resting checked face.
//   DEAD     — nothing (GTK paints no box for an insensitive relief-none
//              button); DEAD AND CHECKED the insensitive active toggle GTK
//              does paint: the disabled ramp (1.04 | 1.01 / 0.99 | 0.96 of
//              bg), the inset ring, the inner shadow, the shade[4] border,
//              displaced like a checked one.
// Answers the glyph's shift in device px.
int paint_cl_tool_button(cairo_t* cr, const GuiRect& r, bool lamp,
                         bool pressed, bool hot, bool enabled);

// -- THE DIALOGS, THE DROPDOWN AND THE LIST (the painters round's second
//    part, 2026-10-07) --------------------------------------------------------

// ONE PUSH BUTTON — clearlooks_gummy_draw_button on the "button" style
// (xthickness 3, reliefstyle 1) on the dialog button's box `r`, its W
// height the spec's push_button_box_px:
//   NORMAL   — bg[NORMAL] (1.04): the two shadow rings of the parent's bg
//              (0.97, 0.93), the gummy ramp, the border mix (shade[6], fill,
//              0.2) of the button style's table, the baked 0.4 top-left
//              highlight.
//   PRESSED  — bg[ACTIVE] (0.85): the parent's inset ring, the ramp, the
//              baked inner shadow over its first three rows and columns, the
//              border; the label one W px right and down.
//   DISABLED — bg[INSENSITIVE]: the inset ring, the disabled ramp (1.04 |
//              1.01 / 0.99 | 0.96), the button style's shade[4] border, the
//              highlight; the label the caller's insensitive pair.
//   DEFAULT  — `is_default` (the button Enter answers — the button the
//              Windows arm frames in DkShadow): ONE ring mix (parentbg,
//              spot[1], 0.5) for the two shadow rings and the border mix
//              (spot[2], fill, 0.2); pressed, the inset over that ring and the
//              spot border; a disabled button is never drawn default (the
//              engine's `is_default && !disabled`).
// NO HOT FACE: the dialog buttons have no hover (the toolbars' HOT case is
// the one hover face, the head) and GTK's focus ring is not drawn (the
// product draws no focus ring: the default face is the cue). Answers the
// label's shift in device px.
int paint_cl_push_button(cairo_t* cr, const GuiRect& r, bool pressed,
                         bool enabled, bool is_default);

// ONE ENTRY — clearlooks_gummy_draw_entry on the "entry" style (xthickness
// 3) on the dialog field's box `r`: the parent's inset ring at radius + 1,
// base[NORMAL] inside at radius − 1; UNFOCUSED the shade[6] border at the
// radius and the inner shadow (shade (border, 0.92) at 0.18, baked over
// base) along the top and the left; FOCUSED (the field the caret is in) the
// entry style's focus_color border and the inner ring mix (base, shade
// (focus_color, 1.61), 0.5). The text, the selection and the caret are the
// caller's, in cl_text, cl_selection / cl_selection_unfocused under
// cl_text_selected (GtkEntry's own pairs) and cl_text.
void paint_cl_entry(cairo_t* cr, const GuiRect& r, bool focused);
// The same entry on a caller's base: the time fields' `clock_ground`
// (paint_time_field — the clock pair is the GNOME entry's base / text under
// the clearlooks theme, gen_theme_files' CLOCK_FROM_FIELD). The ring and
// the border are the entry's own roles.
void paint_cl_entry(cairo_t* cr, const GuiRect& r, bool focused,
                    GuiColor base);

// THE DROPDOWN'S BOX — GtkMenu under the "menu" style: its ground
// (bg[NORMAL] 1.08 of bg) and clearlooks_draw_menu_frame's one shade[5]
// line round it, THE TOP LINE ONE ROW ABOVE `box`, on the menu row's last
// row: GTK's menu covers the menu bar's foot and the open title's (his
// capture 23-22-06), and the box's published rect, every hit rect, stays
// where the menu row ends (paint_dropdown; the open and the close damage
// the top strip, so that row is repainted with the box). An `upward` box —
// a list standing on its combo's head (combo_list, color_picker.h) —
// carries the top line on its OWN first row instead (2026-10-08:
// popup_border_top_px's rule; nothing above it is repainted with the box).
// The items stand against the frame (x / ythickness 0) and a lit one covers
// it.
void paint_cl_menu(cairo_t* cr, const GuiRect& box, bool upward);

// THE LIT MENU ITEM — clearlooks_gummy_draw_menuitem on the item's box:
// spot[1]'s gummy ramp over the item's whole height inside a one-W spot[2]
// border at the menu's radius 0, square. The label over it is the caller's,
// in cl_menuitem_text.
void paint_cl_menu_item(cairo_t* cr, const GuiRect& item);

// THE SEPARATOR ITEM'S LINE — clearlooks_draw_menu_item_separator: ONE
// shade[5] row, no light line, at device row `y` across [x, x + w).
void paint_cl_menu_separator(cairo_t* cr, int x, int y, int w);

// THE LIST'S FIELD — a GtkTreeView in a GtkScrolledWindow, shadow IN, under
// GUMMY (clearlooks_style_draw_shadow's "scrolled_window" arm; his compact
// view, 00-17-47): base[NORMAL] on `surf` inside ONE square shade[5] line on
// its outer rows and columns (folder_overlay::content_rect spends the one
// line).
void paint_cl_list(cairo_t* cr, const GuiRect& surf);

// A SELECTED ROW — clearlooks_gummy_draw_selected_cell on the row's box:
// the gummy ramp of base[SELECTED] while the list has the focus, of
// base[ACTIVE] (shade (sel, 0.9)) while it has not, over the row's whole
// height, no border, square. The name over it is the caller's, in
// cl_text_selected.
void paint_cl_selected_cell(cairo_t* cr, const GuiRect& r, bool focused);

// -- THE LANES, THE SCRUB, THE STATUS BAR AND THE FRAME (the painters round's
//    last part, 2026-10-07) ----------------------------------------------------

// GTKSCALE'S LENGTHS (the default style's GtkScale::slider-length 23 and
// GtkRange::slider-width 15; clearlooks_draw_gummy.c's TROUGH_SIZE 7), in
// Windows px — the scrub's drawing under clearlooks (paint_cl_scale_trough,
// paint_cl_scale_thumb below). The thumb's grab box is the spec's
// scrub_handle_box_px, the same 23 (asserted in clearlooks_paint.cpp).
inline constexpr int kClScaleTroughPx       = 7;
inline constexpr int kClScaleSliderLengthPx = 23;
inline constexpr int kClScaleSliderWidthPx  = 15;

// THE TRIM CAP'S RAMP LENGTH, in Windows px: the ring of each cap
// (paint_cl_stepper below) turns from the light tone to the dark over its
// first kClCapRampPx rows and is the dark tone flat below them — 15 % of the
// 16-W box (architect 2026-10-07 evening, the TC2 sheet's step j: "the ramp
// starts in the top row and ends early", so the whole turn falls inside the
// outer corner's arc and the straight outer column carries no gradient).
// Converted at the element (scaled_px): 2 rows at 100, 3 at 138, 7 at 300.
inline constexpr double kClCapRampPx = 2.4;

// THE TRIM LANE IS GTK'S HORIZONTAL SCROLL BAR — ITS TROUGH — round the
// product's own light bar: the body between the caps the light slider
// (paint_cl_slider below) and the caps in step with it (paint_cl_stepper
// below, 2026-10-07 evening) — (architect 2026-10-07, the painters round's
// last part; render.h's trim block keeps every rect: the lane, the two caps'
// 16 x 16 boxes where trim_endcap_rect puts them, the body between them, the
// hit stash). THE BAR WEARS THE LANE'S 16 W ROWS,
// Windows' SM_CYHSCROLL, where GTK's is 15 (GtkRange::slider-width and
// stepper-size 15): one row more of every ramp below, the base's thickness
// kept (the settled rule: the proportional fit to Windows' layout).
//
// THE TROUGH — clearlooks_draw_scrollbar_trough (gummy keeps the classic
// one), its vertical frame's axes exchanged: across the lane `lane`
// shade[2], its first and last rows the shade[5] border, and under the top
// border the shadow — a linear gradient shade (shade[2], 0.95) -> shade[2]
// from row 1 to row 3 whose rows 1 and 2 show (row 3 on is the fill, the
// source's own arithmetic; build.py records the two rows). NO END COLUMNS:
// GTK's trough ends under its steppers (trough-under-steppers), and the
// lane's ends are the window's, past which the bar runs on as its body does
// (render_trim_flags' OFF SCREEN rule) — so the border is the two rows.
void paint_cl_trough(cairo_t* cr, const GuiRect& lane);

// ONE CAP, THE PRODUCT'S OWN, IN STEP WITH THE LIGHT BAR (architect 2026-10-07
// ~16:40, on the glass, of the gummy stepper this replaces — its shade[7]
// border ring dark along its whole top row against the body's light line:
// "the trim end caps look tacked on ... misaligned. They need to start with
// a light side at the top, and the curve that forms the outer edge of each
// end cap needs to start on a light tone and then darken as it goes down, to
// imitate the reflection of light"; and ~17:10: "be careful that there is
// some contrast between the trim end cap and the body, at least in the top
// part — we don't want it to blur together either"; the TC1 sheet's variant
// c) on a trim cap's box `b` (trim_endcap_rect's 16 x 16): THE RING, one W
// wide, is the bar's own two tones — THE ONE RAMP from `cl_separator_light`
// (the body's light line continued) to `cl_separator_dark` (its dark line
// continued) over the box's first kClCapRampPx rows, its first row the
// light tone itself (paint_cl_ramp, rule 2 of the head), and every row
// below the ramp the dark tone flat, the bottom row included — so its two
// OUTER corners, rounded at the spec's radius (the begin cap's left ones, the
// end cap's right: GTK's stepper A and D, the corners at the bar's ends),
// start light and darken along the curve. THE RAMP ENDS EARLY (architect
// 2026-10-07 evening, the TC2 sheet's step j): a ramp over the whole height
// drew the eye at any distance and made the straight outer column read
// SLANTED, the begin cap's left line leaning right from bottom to top — the
// gradient down a straight column is the lean; ended inside the corner's
// arc, the darkening runs along the curve "up and to the right" and the
// straight column is one tone. THE FACE inside, its corners
// concentric, is the window ground at rest (the bar's own, a button in the
// bevel, not a gummy box on it) and `cl_stepper_pressed_face` pressed —
// bg[ACTIVE] of the scrollbar style, the default style's shade (0.9,
// bg_color), his capture 00-12-13's pressed stepper, flat here; THE INNER
// EDGE, where the cap meets the body, one W of the dark tone the lane's
// whole height — the contrast his caveat asks for, a dark cell notching the
// light line at the top so the cap reads as a button against the body (the
// sheet's variant e, without it, blurred into the body at rest). Every
// tone a role: the ring's two are reused by the light bar's own ruling
// (paint_cl_slider), the pressed face the one tone added (the gummy
// stepper's own tones are the popup lists' bar's, paint_cl_scrollbar_stepper
// below, not the trim lane's). THE ARROW stays the engine's own, kept by ruling
// (clearlooks_draw_normal_arrow, its chevron filled in fg) at GtkRange's
// arrow-scaling 0.5 of the 16-W box — 8 W, so the engine's 8-wide,
// 4.75-tall wedge, its line half-width 0.75 — centered on the box, pointing
// left on the begin cap and right on the end cap; GTK displaces no arrow
// (GtkRange::arrow-displacement 0): pressed, only the face changes. NO
// HOVER FACE (the one hover face is the toolbars').
void paint_cl_stepper(cairo_t* cr, const GuiRect& b, bool points_left,
                      bool pressed);

// THE BODY IS THE PRODUCT'S OWN LIGHT SLIDER, A RECORDED DEPARTURE FROM
// SQUEEZE'S GUMMY ONE (architect 2026-10-07, the CL15 sheets: "Clearlooks is
// anonymous enough that we can get away with our own scroll bar") on the
// body rect `body` (render_trim_flags' gap, the bridge, the kept region
// between the caps): THE WINDOW GROUND, `ground`, with ONE W px of
// `cl_separator_light` (FCFCFC, shade (shade[3], 1.3)) along its top row and
// ONE W px of `cl_separator_dark` (C4C2BF, shade[3]) along its bottom row —
// NO GRIPS, no ring, no ramp and no border columns at its ends: the caps ride
// the body's ends, so an end column would never show, and a cap sliding off
// the window takes the body's end with it (render_trim_flags). The two lines
// are the gummy separator's own tones, roles already made for
// paint_cl_toolbar_separator: a role a second painter reads is that tone put
// down again, not a color derived here. The trough stays GTK's (above); the
// caps wear the same two tones (paint_cl_stepper, since the evening). (Gummy's
// spot[1] slider, its ring and its three grips are the popup lists' bar's —
// paint_cl_scrollbar_slider below, 2026-10-08 — never the trim lane's.)
void paint_cl_slider(cairo_t* cr, const GuiRect& body);

// THE POPUP LISTS' VERTICAL SCROLL BAR (architect 2026-10-08; the rule and
// the geometry at render.h's popup scroll block, the dispatch
// paint_popup_scroll_bar) — SQUEEZE'S OWN GUMMY GtkScrollbar AS THE ENGINE
// DRAWS IT (architect 2026-10-08 ~12:50, reversing the morning's trim-lane
// bar turned upright: "I had asked you to use the official Clearlooks scroll
// bar, the normal one in the squeeze folder — this is the one from the trim
// bar, it doesn't work here"; his captures 00-17-24, Nautilus' list bar, and
// 00-12-13, a pressed stepper, the law, reproduced byte for byte at GTK's 15
// by build.py's arithmetic), at the base's 16 W wide; THE TRIM LANE KEEPS
// ITS OWN CAPS AND LIGHT SLIDER (above; their ruling stands). A RECORDED
// DEPARTURE FROM GTK (architect 2026-10-08, on squeeze's Country combo,
// tmp/Screenshot_2026-10-08_05-20-01.png): GtkComboBox's overflowing popup
// scrolls with a scroll ARROW at its top and its bottom, which he rejects —
// "I'd much rather have the scroll bar inside, and we can use the canonical
// scroll bar" — so a Clearlooks list wears the scroll bar GTK's own
// scrolled lists wear, inside its frame at its right
// (docs/engineering/win2000_deviations.md). Every ramp runs ACROSS the bar,
// left to right, each tone a role (build.py's engine_tones, the
// cl_scrollbar_* block), interpolated by the one rule (paint_cl_ramp_across).
//   THE TROUGH (paint_cl_scroll_trough_v) on `bar`: clearlooks_draw_
//     scrollbar_trough, the classic one gummy keeps — cl_trough_fill, its
//     first and last COLUMNS the cl_trough_border, and right of the left
//     border the shadow's two graded columns (W columns 1 and 2, the
//     horizontal trough's two rows turned); no end rows. The caller hands it
//     the bar less 2 W at each end, the engine's own shrink under its
//     steppers (trough-under-steppers), so the steppers' rounded outer
//     corners show the list's ground behind them, as GTK's show the window's.
//   THE STEPPERS (paint_cl_scrollbar_stepper) on the arrow boxes —
//     clearlooks_gummy_draw_scrollbar_stepper: the fill inside the box one W
//     in, bg[state]'s gummy ramp across (`_left` over W columns 1 .. step − 1,
//     `_right` over step .. 14, the step at column 8 where pixman put it);
//     the top-left highlight, shade (fill, 1.3) at 0.4 baked over the ramp
//     (draw_top_left_highlight): down W column 1 in its first tone, round a
//     rounded top-left corner and along W row 1 across the ramp's columns;
//     the border mix (shade[7], fill, 0.2) one W round the box; the OUTER
//     corners rounded at the spec's radius (the up stepper's top two, the
//     down stepper's bottom two, GTK's steppers A and D). RESTING bg[NORMAL],
//     PRESSED the scrollbar style's bg[ACTIVE] (the capture 00-12-13's
//     pressed stepper); no prelight (the one hover face is the toolbars'),
//     and GTK displaces no arrow. THE ARROW the engine's chevron in fg, the
//     trim caps' own (GtkRange's arrow-scaling 0.5 of the 16-W box).
//   THE SLIDER (paint_cl_scrollbar_slider) on the thumb's painted rect —
//     clearlooks_gummy_draw_scrollbar_slider with colorize_scrollbar TRUE:
//     spot[1]'s gummy ramp across the fill (W columns 1 .. 14, the step at
//     column 8), the highlight shade (fill, 1.3) at 0.2 baked over the ramp
//     ONE W IN ON ALL FOUR SIDES (has_color's stroked rectangle: its top and
//     bottom rows the baked ramp, its left and right columns the ramp's end
//     tones), the border one W round it square, and THE THREE GRIPS, one W
//     each in the grip tone, across W columns 5 .. 10 (the engine's 5 to
//     height − 6, both ends whole as his capture draws them) at W rows
//     L / 2 − 4, + 3 and + 6 of its length L. THE JUNCTION (the engine's
//     CL_JUNCTION_BEGIN / END): a slider touching an end of the track runs
//     one W on under that stepper, whose border row, drawn after it, covers
//     the slider's own — so a slider at the head shows its highlight row
//     straight under the stepper's border, never a doubled line (the caller
//     extends the rect; paint_popup_scroll_bar).
//   GtkScrollbar::min-slider-length 30 floors the thumb
//     (kPopupScrollThumbMinClPx, render.h).
void paint_cl_scroll_trough_v(cairo_t* cr, const GuiRect& bar);
void paint_cl_scrollbar_stepper(cairo_t* cr, const GuiRect& b, bool points_up,
                                bool pressed);
void paint_cl_scrollbar_slider(cairo_t* cr, const GuiRect& body);

// THE WELL'S FRAME — GtkScrolledWindow's shadow IN under GUMMY
// (clearlooks_style_draw_shadow's "scrolled_window" arm, P2's list frame:
// ONE shade[5] line, cl_list_frame) on the well's top and bottom rows of the
// waveform area `area` (render_canvas, which takes the frame's two lines a
// side FROM the area under both chromes, waveform_border_px): the OUTER line
// of each pair is the scrolled window's, the inner one the canvas the
// window's child begins on — GTK's one line at the base's thickness. THE
// WELL'S EDGES ARE THAT ONE LINE AND NOTHING ELSE (architect 2026-10-07
// ~05:30: "Clearlooks is friendlier to flat one-pixel one-colour borders —
// the file manager's main panel is just a one-pixel line all around"): his
// Nautilus captures 00-17-24 and 00-17-47 show the list's ground, ONE frame
// line, then the window's ground above it and the status bar's ground below
// it — so row 8 under the well draws no line of its own (paint_bottom_strip;
// the gummy status bar's own two-line frame, clearlooks_gummy_draw_statusbar,
// which his Music Player capture 23-12-32 shows under its list, is not the
// file manager's).
void paint_cl_well_frame(cairo_t* cr, const GuiRect& area);

// THE SCRUB'S TROUGH — clearlooks_gummy_draw_scale_trough on `trough`, the
// kClScaleTroughPx rows across the track (cl_scale_trough_h_px tall), SQUARE
// (the scale passes radius 0): THE UPPER PART right of `split` (the thumb's
// centre column; the track's left edge when no thumb stands) draw_inset's
// ring (shade 0.94 / 1.06 of the window's bg, split on the diagonal — P2's
// inset ring), a one-W border mix (shade[6], fill, 0.2) inside it, and the
// fill shade (bg, 0.896) under the "in" ramp 0.95 -> 1.05; THE LOWER PART
// left of it (GtkScale::trough-side-details, "trough-lower" — the volume
// slider's blue) the same in spot[1] under the "out" ramp 1.1 -> 0.9 inside
// mix (spot[2], spot[1], 0.2). Each part closes its own ends, as GTK's two
// boxes do, the thumb covering the seam.
void paint_cl_scale_trough(cairo_t* cr, const GuiRect& trough, int split);

// THE SCRUB'S THUMB — clearlooks_gummy_draw_slider_button on `box`, the
// slider-length x slider-width box (cl_scale_thumb_w_px x _h_px) centred on
// the trough (4 rows above it, its 7, 4 below; GTK centres the trough in the
// range's height): draw_shadow's stroke down the box's last column and along
// its last row, round the bottom-right corner at the slider's radius 3, its
// 0.1 alpha baked over what it crosses (the ground, and the upper trough's
// rows — the inset ring, the border, the ramp); then
// clearlooks_gummy_draw_slider one W in: bg's gummy ramp, the border mix
// (shade[7], fill, 0.2) at THE SOURCE'S RADIUS 2.5 (kClScaleSliderRadiusPx,
// the engine's own literal — the spec's 3 is the gtkrc's), three shade[7]
// grip bars on the engine's columns, the top-left highlight at radius 2,
// baked. No prelight (the one hover face is the toolbars').
void paint_cl_scale_thumb(cairo_t* cr, const GuiRect& box);
int  cl_scale_trough_h_px();
// (cl_scale_thumb_w_px / cl_scale_thumb_h_px are declared in render.h's
// scrub block, beside the accessor that reads the height.)

// THE RESTORED LAPTOP'S FRAME — metacity's `normal` frame style set
// (gnome-themes 2.30.2's Clearlooks: `focused` = round_bevel, `normal` =
// round_bevel_unfocused, on the `normal` geometry) painted on the whole
// surface, `surface_w` x `surface_h` device px with its origin at (ox, oy),
// the sizing frame `frame_px` thick (platform_wayland.cpp's frame_px_,
// window_frame_px), the caption lane `caption_h` device rows under its top
// band. THE GEOMETRY AGREES WHERE IT CAN: metacity's left, right and bottom
// widths are 4, the platform's frame is 4 (Windows' SM_CXSIZEFRAME), so the
// band is as before; METACITY HAS NO TOP BAND — its title bar is the frame's
// top — so the platform's 4-W top band and the caption lane under it are ONE
// TITLE BAR, top_height 4 + 20 = 24 (squeeze's own at Sans 10, by
// coincidence of the two cells), title_height 17, every title op at its
// metacity row: the band's rows 0 .. 3 metacity's 0 .. 3, the caption
// lane's rows 0 .. 19 its 4 .. 23. The frame's width is a hit length the
// platform owns (window_frame_edges_at): nothing moves. THE ROUNDED TOP
// CORNERS: metacity cuts them (rounded_top_left / _right, its radius-5
// shape) and draws the corner art inside the cut — corners_outline_* (five
// cells a corner: three dark on the diagonal, two in-between) and
// corners_highlight* (four cells one W further in) — whose cells trace a
// quarter circle centred five W in from each edge: drawn AS THAT ARC, one
// antialiased W-px stroke of the outline's dark tone at radius 4.5 W (the
// cut's edge less half a line) and one of the highlight's at 3.5 W (on the
// top-right, its two tones meeting at 45 degrees, as the art's two pairs
// do), the surface CLEARED outside the cut (the ARGB surface's own shape,
// metacity's mask); the art's in-between cells are the antialiasing the arcs
// do themselves. The caption lane's own painter calls this with its origin
// at the lane less the frame (paint_caption_row) so the two halves of the
// title bar are one picture.
void paint_cl_window_frame(cairo_t* cr, int ox, int oy, int surface_w,
                           int surface_h, int frame_px, int caption_h,
                           bool focused);
