#pragma once

#include "render.h"   // GuiRect, GuiColor, palette(), scaled_px

#include <cairo.h>

// THE CLEARLOOKS PAINTERS (architect 2026-10-07, the painters round's first
// part: the top strip) — the chrome spec's clearlooks arm (chrome_spec.h),
// GNOME 2.30's own drawing as Debian 6 squeeze put it on screen: the
// metacity theme's maximised caption (gnome-themes 2.30.2's Clearlooks
// metacity-theme-1.xml), and gtk-engines 2.20.2's Clearlooks GUMMY style for
// the menu bar, the toolbar band, its tool buttons and separators
// (clearlooks_draw.c, clearlooks_draw_gummy.c), his squeeze captures the law
// (tmp/squeeze/). Every painter here is called from its win2000 sibling's
// site on the spec's fork (paint_handler.cpp) and reads its lengths from the
// live spec, so a length changed at the instance moves the drawing with no
// edit here (and the tones with one re-run of tools/theme_catalog, which
// reads the same instance).
//
// FOUR RULES OF THE PALETTE HEAD BEND FOR THIS VOCABULARY ONLY (report CL1
// §4; render.h's palette head names this block as the bend's one statement),
// THE WIN2000 PAINTERS UNTOUCHED BY ALL FOUR:
//   1. EVERY COLOUR IS A ROLE STILL, generated by need: the `cl_` block of
//      the role table (theme_file.h, theme_clearlooks_roles.inc), each byte
//      the engine's own arithmetic run once at import (tools/theme_catalog
//      build.py's engine tones). These painters read no other role but
//      `ground` (the window's bg, the same surface in both vocabularies).
//      The relief quartet, the mitre and the paint_relief_* families are
//      Windows' and are never read here (CL1 §4.5).
//   2. RAMPS BETWEEN RECORDED STOPS (CL1 §4.1; the planner's decision): the
//      engine's and metacity's vertical gradients, each painted by
//      paint_cl_ramp below — THE ONE INTERPOLATION RULE, the caption
//      gradient's own (paint_caption_gradient) turned vertical: device row i
//      of n takes round(s + (e − s)·i/(n − 1)) per channel, s and e the
//      segment's two stop roles, which are THE FIRST AND LAST ROWS THE
//      PERIOD PAINTED (the import's record), so at 1 W px the ends are the
//      captures' pixels and every row between lands within one level of the
//      period's (build.py asserts it). A one-row line is a fill.
//   3. ALPHA IS BAKED AT IMPORT, NEVER AT PAINT TIME (CL1 §4.3): where the
//      engine strokes a translucent colour over a known fill — the gummy
//      button's 0.4 top-left highlight, the pressed button's 0.58 -> 0 inner
//      shadow — the import composites it over that fill's recorded row and
//      records the result as a role (per row, or per column as a ramp's
//      ends); every byte painted here is opaque. ANTIALIASED EDGES ARE THE
//      RENDERER'S, as everywhere (the rounded corners' arcs, the Close
//      glyph's diagonals, the inset's diagonal split).
//   4. ROUNDED CORNERS (CL1 §4.2): the gummy boxes' corners are the spec's
//      corner_radius_px (the gtkrc's `radius = 3.0`), scaled like any length
//      and drawn as antialiased cairo arcs; win2000's radius is 0.
// AND ONE HOVER FACE MORE IS NOT ADDED (CL1 §4.6): the toolbar's HOT case
// (GTK's prelight) stays the one hover face; the menu bar's prelit title and
// the caption buttons' prelight are not drawn (metacity's button_bg_prelight
// and GTK's prelit menu title would be two new hover faces).
//
// THE GEOMETRY MAPS AT THE ELEMENT (render.h's scaled_px rule): an authored
// W-px coordinate k of a box at device origin o stands at o + scaled_px(k),
// every edge rounded on its own, so the box's parts tile it exactly; the
// gummy button's one-W lines are relief_line_px() wide, as every one-W line
// in the chrome.

// THE ONE RAMP RULE (rule 2 above): `r` filled top to bottom, device row i
// of r.h in round(top + (bottom − top)·i/(r.h − 1)) per channel (std::
// nearbyint, the tree's one rounding), each row one opaque cell rect, so a
// clip cuts it like any fill. Cannot fail.
void paint_cl_ramp(cairo_t* cr, const GuiRect& r, GuiColor top,
                   GuiColor bottom);

// THE CAPTION'S BAND — metacity's `bevel_maximized` (focused, shades of
// bg[SELECTED]) or `bevel_maximized_unfocused` (shades of bg[NORMAL]) on the
// lane `lane` (render.h's caption block): ROW 0 the 0.55 edge; UNFOCUSED,
// ROW 1 the 1.05 light line (focused, the upper gradient covers its 1.18
// line, as his captures show); the UPPER gradient down to row H/2 − 1, the
// LOWER from H/2 to H − 2 (covering the 0.94 / 0.89 line at H − 2); ROW
// H − 1 the 0.7 / 0.65 foot — H the spec's caption_height_px, the band's
// rows proportional to it (metacity's own top_height / 2 arithmetic).
void paint_cl_caption_band(cairo_t* cr, const GuiRect& lane, bool focused);

// The caption buttons' glyph (metacity's *_button_icon draw_ops).
enum class ClCaptionGlyph { Minimize, Maximize, Restore, Close };

// ONE CAPTION BUTTON on its box `b` (caption_button_rects, its W size the
// spec's caption_button_w_px x caption_button_h_px): metacity's button_bg
// (focused) / button_bg_unfocused, or their _pressed sets while `pressed`,
// op for op in the theme's order (each line a role, each gradient a ramp
// between two), then the glyph at metacity's icon_size = Bmin 7 `max`
// (height − Bpad 6 x 2), centred — focused, the 0.7 outline under the
// blend(sel, white, 0.75) shape; unfocused, the blend(fg, bg, 0.45) shape
// alone. CLOSE'S DIAGONALS are antialiased strokes from pixel centre to
// pixel centre at their recorded widths (4 under 2 + 1, butt caps, the
// tints' square ears), the scalable form of X's wide lines; every other
// glyph part is a cell rect. NO PUSH: metacity draws the pressed glyph in
// place. A DISABLED BUTTON (the tablet's Restore, which cannot restore:
// metacity draws no disabled button, it hides one) keeps its box and wears
// the unfocused glyph — the window manager's own "not yours now" ink (the
// planner's reading, 2026-10-07).
void paint_cl_caption_button(cairo_t* cr, const GuiRect& b,
                             ClCaptionGlyph glyph, bool focused, bool pressed,
                             bool enabled);

// THE MENU BAR'S GROUND — clearlooks_draw_menubar2 (menubarstyle 2) on the
// lane: the bg -> bg x 0.96 ramp down every row but the last, and the last
// row shade[3], the line between the menu bar and the toolbar.
void paint_cl_menubar(cairo_t* cr, const GuiRect& lane);

// THE OPEN MENU TITLE — clearlooks_gummy_draw_menubaritem on the anchor
// whose dropdown is down: x and width the anchor's, its rows the content's
// plus one (the style passes height + 1, so its foot is the bar's shade[3]
// row), the TOP corners rounded at the spec's radius: spot[1]'s gummy ramp
// (1.08 | 1.02 / 1.0 | 0.94) inside a one-W spot[2] border. The label over
// it is the caller's, in cl_menubaritem_text, unpushed.
void paint_cl_menubar_item(cairo_t* cr, const GuiRect& lane, int x, int w);

// THE TOOLBAR BAND — clearlooks_gummy_draw_toolbar (toolbarstyle 1, not
// topmost: it stands under the menu bar) on `band`, the icon row's band and
// row 8's: its first row bg x 1.1, the 1.04 | 1.01 / 1.0 | 0.97 ramp with
// its step at the band's middle, its last row shade[3].
void paint_cl_toolbar_band(cairo_t* cr, const GuiRect& band);

// THE GROUP GAP'S SEPARATOR — clearlooks_gummy_draw_separator, vertical, in
// the gap starting at `gap_x` over the case [case_y, case_y + case_h): a
// shade[3] column at the spec's toolbar_separator_x_px and its 1.3 column
// beside it, inset toolbar_separator_inset_y_px at each end
// (_gtk_toolbar_paint_space_line's 20 % to 80 %).
void paint_cl_toolbar_separator(cairo_t* cr, int gap_x, int case_y,
                                int case_h);

// ONE TOOL BUTTON — GtkReliefNone in a toolbar (chrome_spec.h's
// GtkReliefNone), clearlooks_gummy_draw_button on the button style
// (xthickness 3, reliefstyle 1) where GTK paints a box at all:
//   REST     — nothing: the glyph on the band.
//   HOT      — the prelit button (bg[PRELIGHT], 1.06): the two shadow rings
//              of the parent's bg (0.97, 0.93), the gummy ramp, the border
//              mix (shade[6], fill, 0.2), the baked 0.4 top-left highlight.
//   PRESSED / CHECKED — the active button (bg[ACTIVE], 0.85): the parent's
//              inset ring (0.94 top-left / 1.06 bottom-right, split on the
//              diagonal), the ramp, the baked inner shadow over its first
//              three rows and columns, the border; the glyph one W px right
//              and down (GtkButton::child-displacement 1).
//   HOT AND CHECKED — GTK's prelit active toggle: the active button in
//              bg[PRELIGHT].
//   DEAD     — nothing (GTK paints no box for an insensitive relief-none
//              button); DEAD AND CHECKED the insensitive active toggle GTK
//              does paint: the disabled ramp (1.04 | 1.01 / 0.99 | 0.96 of
//              bg), the inset ring, the inner shadow, the shade[4] border,
//              displaced like a checked one.
// Answers the glyph's shift in device px.
int paint_cl_tool_button(cairo_t* cr, const GuiRect& r, bool lamp,
                         bool pressed, bool hot, bool enabled);
