#!/usr/bin/env bash
# tools/app_icon/gen_app_icon.sh — assets/icons/mist/AppIcon.svg -> THE PROGRAM ICON OUTSIDE THE WINDOW
# THE ICON (architect 2026-10-07 ~17:00, kept 2026-10-09): the Mist set's AppIcon, gnome-icon-theme 2.30's
# audio-x-generic (its 48 slot extracted from 3.0.0's sheet — assets/icons/mist/README.md), on the ground
# #EDECEB, so both outputs carry that face behind the drawing. (The SVG comment the generator writes names the
# ground by its 2026-10-07 source, the text the committed output carries.) It writes, from the repo root's point of view:
#   packaging/warptempo_gui.svg     the Linux desktop icon (the .desktop's Icon=warptempo_gui; docs/INSTALL.md
#                                   installs it into hicolor's scalable/apps): a 48 x 48 document, a ground-colored
#                                   48 x 48 rect, then AppIcon.svg VERBATIM as a nested <svg> element (its bytes less the
#                                   XML declaration, which may only open a document) — no surgery on the drawing;
#   android/app/res/mipmap-<density>/ic_launcher_{foreground,background}.png
#                                   the Android adaptive icon's two layers (ic_launcher.xml's head holds the
#                                   per-density table and the safe-zone arithmetic): the foreground the drawing
#                                   rasterised ANTIALIASED by rsvg-convert (librsvg) at 64 dp square, centred on
#                                   the transparent 108 dp canvas; the background the 108 dp canvas in the solid
#                                   ground, which the launcher's mask cuts to its shape.
# A ONE-SHOT, NOT A BUILD STEP: the outputs are committed and build_apk.sh only compiles res/. Re-run after any
# change of AppIcon.svg; never hand-edit an output. Byte-stable: rsvg-convert writes no timestamp and ImageMagick's
# -strip drops its date chunks. Needs rsvg-convert and ImageMagick 7's magick on PATH.
#
#   bash tools/app_icon/gen_app_icon.sh
set -euo pipefail
[ $# -eq 0 ] || { echo "usage: bash tools/app_icon/gen_app_icon.sh" >&2; exit 2; }
cd "$(dirname "$0")/../.."

SRC=assets/icons/mist/AppIcon.svg
OUT_SVG=packaging/warptempo_gui.svg
RES=android/app/res
GROUND='#EDECEB'   # the icon's ground (the head)

# The source's shape: line 1 the XML declaration, a 48 x 48 root (its start tag read whole, on one line as the Mist
# extractions write it or across lines as Inkscape does). Anything else is a hard fail (a different drawing size is a
# change to this generator).
head -n 1 "$SRC" | grep -q '^<?xml ' || { echo "gen_app_icon: $SRC: line 1 is not the XML declaration" >&2; exit 1; }
ROOT=$(tr '\n' ' ' < "$SRC" | grep -o '<svg[[:space:]][^>]*>' | sed -n 1p)
grep -q -E '[[:space:]]width="48(\.0+)?(px)?"' <<< "$ROOT" && grep -q -E '[[:space:]]height="48(\.0+)?(px)?"' <<< "$ROOT" \
    || { echo "gen_app_icon: $SRC: not a 48 x 48 drawing" >&2; exit 1; }

# The ground EDECEB is the launcher's own since 2026-10-09: the Clearlooks chrome that named it is removed, and the
# SVG comment below keeps its words so the committed output stays byte-identical.
{
    printf '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48">\n'
    printf '  <!-- The program icon outside the window, the Linux desktop icon (the .desktop'"'"'s\n'
    printf '       Icon=warptempo_gui): the caption'"'"'s AppIcon, GNOME'"'"'s audio-x-generic from the Mist\n'
    printf '       set (its provenance is assets/icons/mist/README.md), on the chrome'"'"'s ground,\n'
    printf '       Clearlooks'"'"' (architect 2026-10-07). GENERATED by tools/app_icon/gen_app_icon.sh from\n'
    printf '       %s, the ground its own and the drawing verbatim after it:\n' "$SRC"
    printf '       regenerate, never hand-edit. -->\n'
    printf '  <rect fill="%s" width="48" height="48"/>\n' "$GROUND"
    tail -n +2 "$SRC"
    [ -z "$(tail -c 1 "$SRC")" ] || printf '\n'   # the Mist extractions end without a newline
    printf '</svg>\n'
} > "$OUT_SVG"
echo "wrote $OUT_SVG"

# density f -> the 64 dp art A = 64f px and the 108 dp canvas C = 108f px (ic_launcher.xml's table).
for row in mdpi:64:108 hdpi:96:162 xhdpi:128:216 xxhdpi:192:324 xxxhdpi:256:432; do
    IFS=: read -r density art canvas <<< "$row"
    dir="$RES/mipmap-$density"
    rsvg-convert --format=png --width="$art" --height="$art" "$SRC" \
        | magick png:- -background none -gravity center -extent "${canvas}x${canvas}" -strip \
            -define png:compression-level=9 -define png:compression-filter=5 \
            "PNG32:$dir/ic_launcher_foreground.png"
    magick -size "${canvas}x${canvas}" "xc:$GROUND" -strip \
        -define png:compression-level=9 -define png:compression-filter=5 \
        "PNG32:$dir/ic_launcher_background.png"
    echo "wrote $dir: art ${art} px on ${canvas} px"
done
