#!/usr/bin/env python3
# tools/desktop_icon/gen_desktop_icon.py — assets/icons/chicago95/16/audio-volume-high.png -> packaging/warptempo_gui.svg,
# THE LINUX DESKTOP ICON (the .desktop's Icon=warptempo_gui; docs/INSTALL.md installs it into hicolor's scalable/apps).
# The picture is the program icon of 2026-10-05 (architect: Chicago95's speaker, which the caption wears at a bitmap
# gui_scale and the tablet's launcher wears scaled nearest-neighbour), drawn as ONE RECT PER OPAQUE PIXEL in a
# 16 x 16 viewBox under shape-rendering crispEdges, so any size the desktop asks for is the same pixel art, never
# smoothed. The source's alpha is 0 or 255 only; anything else is a hard fail (a new upstream file is a ruling).
# Pure Python (zlib, struct): the PNG must be 8-bit RGBA, non-interlaced, as the committed file is.
#
#   python3 tools/desktop_icon/gen_desktop_icon.py      (rewrites packaging/warptempo_gui.svg; byte-stable)
import os, struct, sys, zlib

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join('assets', 'icons', 'chicago95', '16', 'audio-volume-high.png')
OUT = os.path.join('packaging', 'warptempo_gui.svg')


def read_rgba(path):
    """An 8-bit RGBA non-interlaced PNG -> (w, h, rows of (r, g, b, a) tuples)."""
    data = open(path, 'rb').read()
    if data[:8] != b'\x89PNG\r\n\x1a\n': raise SystemExit(f'gen_desktop_icon: {path} is not a PNG')
    pos, idat, ihdr = 8, b'', None
    while pos < len(data):
        n, kind = struct.unpack('>I4s', data[pos:pos + 8])
        body = data[pos + 8:pos + 8 + n]
        if kind == b'IHDR': ihdr = struct.unpack('>IIBBBBB', body)
        elif kind == b'IDAT': idat += body
        pos += 12 + n
    w, h, depth, colour, _, _, interlace = ihdr
    if (depth, colour, interlace) != (8, 6, 0):
        raise SystemExit(f'gen_desktop_icon: {path} is not 8-bit RGBA non-interlaced')
    raw, bpp, stride = zlib.decompress(idat), 4, 4 * w
    rows, prev, i = [], bytearray(stride), 0
    for _ in range(h):
        f, line = raw[i], bytearray(raw[i + 1:i + 1 + stride]); i += 1 + stride
        for x in range(stride):
            a = line[x - bpp] if x >= bpp else 0
            b = prev[x]
            c = prev[x - bpp] if x >= bpp else 0
            if f == 1: line[x] = (line[x] + a) & 255
            elif f == 2: line[x] = (line[x] + b) & 255
            elif f == 3: line[x] = (line[x] + (a + b) // 2) & 255
            elif f == 4:
                p = a + b - c; pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                line[x] = (line[x] + (a if pa <= pb and pa <= pc else b if pb <= pc else c)) & 255
            elif f != 0: raise SystemExit(f'gen_desktop_icon: {path}: filter {f}')
        rows.append([tuple(line[4 * x:4 * x + 4]) for x in range(w)]); prev = line
    return w, h, rows


def main():
    if sys.argv[1:]: raise SystemExit('usage: python3 tools/desktop_icon/gen_desktop_icon.py')
    w, h, rows = read_rgba(os.path.join(REPO, SRC))
    rects = []
    for y, row in enumerate(rows):
        for x, (r, g, b, a) in enumerate(row):
            if a == 0: continue
            if a != 255: raise SystemExit(f'gen_desktop_icon: {SRC}: pixel ({x}, {y}) has alpha {a}, not 0 or 255')
            rects.append(f'  <rect x="{x}" y="{y}" width="1" height="1" fill="#{r:02X}{g:02X}{b:02X}"/>')
    svg = (f'<svg version="1.1" viewBox="0 0 {w} {h}" shape-rendering="crispEdges" '
           'xmlns="http://www.w3.org/2000/svg">\n'
           '  <!-- The desktop launcher icon, the .desktop\'s Icon=warptempo_gui: Chicago95\'s\n'
           '       status/16/audio-volume-high.png, the program icon (architect 2026-10-05), one rect per\n'
           '       opaque pixel. Chicago95 by grassmunk, https://github.com/grassmunk/Chicago95, GPL-3.0 per\n'
           '       upstream (assets/icons/chicago95/README.md). GENERATED by\n'
           '       tools/desktop_icon/gen_desktop_icon.py from ' + SRC.replace(os.sep, '/') + ':\n'
           '       regenerate, never hand-edit. -->\n'
           + '\n'.join(rects) + '\n</svg>\n')
    open(os.path.join(REPO, OUT), 'w', newline='\n').write(svg)
    print(f'wrote {OUT}: {len(rects)} opaque pixels of {w} x {h}')


if __name__ == '__main__':
    main()
