#!/usr/bin/env bash
# Generate the two files every meson dep build needs:
#   $WT_PKGCONFIG_WRAPPER  -- a pkg-config that can only see the staging prefix
#   $WT_CROSS_FILE         -- the meson cross file for aarch64-linux-android
# Both are GENERATED (they carry absolute paths, an NDK version and an API
# level), which is why they live under $WT_ANDROID_ROOT and not in the repo.
# Re-run after changing WT_API or the NDK version. Idempotent.
set -euo pipefail
. "$(dirname -- "${BASH_SOURCE[0]}")/00_env.sh"

[ -d "$WT_TOOLCHAIN" ] || wt_die "NDK not installed -- run 10_fetch_ndk.sh first"
command -v pkg-config >/dev/null || wt_die "host pkg-config missing"
HOST_PKG_CONFIG="$(command -v pkg-config)"

mkdir -p "$(dirname "$WT_PKGCONFIG_WRAPPER")" "$(dirname "$WT_CROSS_FILE")"

cat > "$WT_PKGCONFIG_WRAPPER" <<EOF
#!/bin/sh
# Generated by android/toolchain/40_gen_cross_file.sh -- do not edit.
# Env vars alone are not trusted: meson and autotools both re-export their own
# environments. This wrapper hard-forces the staging libdir so a host .pc can
# never leak into a cross build.
export PKG_CONFIG_DIR=
export PKG_CONFIG_LIBDIR=$WT_PREFIX/lib/pkgconfig:$WT_PREFIX/share/pkgconfig
export PKG_CONFIG_SYSROOT_DIR=
unset PKG_CONFIG_PATH
exec $HOST_PKG_CONFIG "\$@"
EOF
chmod +x "$WT_PKGCONFIG_WRAPPER"
wt_say "wrote $WT_PKGCONFIG_WRAPPER"

cat > "$WT_CROSS_FILE" <<EOF
# Generated by android/toolchain/40_gen_cross_file.sh -- do not edit.
# NDK $WT_NDK_VERSION ($WT_NDK_RELEASE), API $WT_API, $WT_TARGET.
# GNU binutils were removed in NDK r23: llvm-ar / llvm-ranlib / llvm-strip /
# llvm-nm / ld.lld are the only names that exist. (Mesa's widely-copied cross
# file still names aarch64-linux-android-ar and -strip; those do not exist.)

[constants]
tc     = '$WT_TOOLCHAIN'
prefix = '$WT_PREFIX'

[binaries]
c          = tc / 'bin/${WT_TARGET}${WT_API}-clang'
cpp        = tc / 'bin/${WT_TARGET}${WT_API}-clang++'
ar         = tc / 'bin/llvm-ar'
ranlib     = tc / 'bin/llvm-ranlib'
strip      = tc / 'bin/llvm-strip'
nm         = tc / 'bin/llvm-nm'
c_ld       = 'lld'
cpp_ld     = 'lld'
pkg-config = '$WT_PKGCONFIG_WRAPPER'

[properties]
# No exe wrapper is provided on purpose: meson then downgrades every run-check
# to a link-check instead of believing it can execute an aarch64 binary.
needs_exe_wrapper         = true
sys_root                  = tc / 'sysroot'
pkg_config_libdir         = prefix / 'lib/pkgconfig'
# Pins cairo's one cc.run() probe (inside the xlib block, never reached here).
ipc_rmid_deferred_release = false

[built-in options]
c_args        = ['-O3', '-fstack-protector-strong', '-ffp-contract=off', '-I' + prefix + '/include']
cpp_args      = ['-O3', '-fstack-protector-strong', '-ffp-contract=off', '-I' + prefix + '/include']
c_link_args   = ['-L' + prefix + '/lib', '-Wl,--as-needed', '-Wl,-z,relro,-z,now', '-Wl,--enable-new-dtags']
cpp_link_args = ['-L' + prefix + '/lib', '-Wl,--as-needed', '-Wl,-z,relro,-z,now', '-Wl,--enable-new-dtags']
prefix        = prefix

[host_machine]
# system = 'android' is load-bearing three times over: it makes meson emit
# UNVERSIONED libfoo.so (android's loader cannot load libfoo.so.2 out of an
# APK), it forces PIE, and it keeps cairo from building its LD_PRELOAD trace
# util. Writing 'linux' here silently breaks all three.
system     = 'android'
cpu_family = 'aarch64'
cpu        = 'aarch64'
endian     = 'little'
EOF
wt_say "wrote $WT_CROSS_FILE"
