#!/usr/bin/env python3
# tools/theme_catalog/gen_theme_files.py — docs/themes/catalog.json -> assets/themes/<key>.theme, THE BUNDLED THEME
# FILES (architect 2026-10-04: every theme but the one built-in ships as a file bundled with the app; 2026-10-05: the
# app copies the bundle into its themes/ folder at every launch, src/gui/theme_file.h's head). One file per catalog
# entry EXCEPT `windows-2000-standard`, the compiled built-in since 2026-10-06 (a file of that name is the launch's
# hard fail; `windows-95-standard` is an ordinary file), so the folder holds exactly the catalog's other entries and
# nothing else: a stale file is deleted.
#
# A FILE NAMES THE ROLES THE ENTRY RECORDS (the grammar, theme_file.h's head: `role=value` lines; a role a file does
# not name takes the built-in's value), each value the entry's recorded byte, nothing derived:
#   THE CHROME, the entry as recorded (roles.light_roles, the one light-roles function): ground, label, the relief
#     quartet (hilight, light_3d, shadow, dk_shadow), the selected pair (a CDE entry's its title_active under colour
#     set 1's Motif foreground, light_roles' rule) and the field pair.
#   THE CLOCK PANEL, clock_ground / clock_text = the entry's ground and label: Windows' status bar is ButtonFace /
#     ButtonText, a mapping by Windows' own rule (the built-in's own two roles are the same pair); A GNOME 2 ENTRY'S
#     its field pair (CLOCK_FROM_FIELD, architect 2026-10-07: GTK has no sunken status panel, and a time shown in a
#     field is an entry, base / text).
#   THE CAPTION (architect 2026-10-05), the six caption roles = the entry's recorded title colours (roles.caption_roles,
#     the one caption mapping: Windows' ActiveTitle / GradientActiveTitle / TitleText and the inactive three, KDE 3's
#     active / inactive background and foreground, CDE's colour sets 1 and 2 under their Motif foregrounds), A
#     GRADIENT END ONLY WHERE THE ENTRY RECORDS ONE: no end line otherwise, and the app's theme-file rule makes the end
#     the start (a flat caption, src/gui/theme_file.h's head), which resolved_roles below applies too.
#   THE CARD, card_ground / card_text = the entry's recorded info pair (roles.py: Windows' InfoWindow / InfoText; the
#     two Windows families record it, KDE 3 and CDE have no tooltip pair), unnamed where the entry records none. card_frame = the entry's recorded info_frame where it records one
#     (GNOME 2: Clearlooks' tooltip border, shade 0.6 of the tooltip's ground), else unnamed: the built-in's black is
#     Windows' tooltip border, and no other entry records a frame colour of its own (every Windows entry's raw
#     WindowFrame is #000000, which no role reads).
#   NO PROGRAM ROLE (architect 2026-10-07): the program's colors are no theme's — they are THE PALETTE's, a file type of
#     its own with two compiled defaults (src/gui/palette_file.h) — so a file names chrome roles only, and the app
#     refuses a theme file naming a program role. `warptempo` and his picker presets, the entries that named them,
#     left the catalog the same day ("it'll still be in the git history"), and this script imports nothing from
#     tools/palette.
#
#   THE CLEARLOOKS PAINTERS' TONES (architect 2026-10-07, the painters round): a GNOME 2 entry's `engine_tones`
#     (build.py engine_tones: the Clearlooks engine's and metacity's own arithmetic at the product's geometry), every
#     one named, after the table's other roles. THEY ARE ALSO THE ROLE TABLE'S CLEARLOOKS BLOCK: this script writes
#     the two GENERATED INCLUDES src/gui/theme_clearlooks_roles.inc (the kGuiThemeRoles rows, each tone's byte the
#     built-in's) and src/gui/theme_clearlooks_members.inc (the GuiPalette members), so a tone joining or leaving is
#     build.py, then this, then the build — never a hand edit of either include.
#
# BYTE-STABLE: the roles in the role table's order (kGuiThemeRoles, src/gui/theme_file.h, read here and checked
# against ROLE_ORDER), uppercase `#RRGGBB`, LF, no timestamp; run it twice and the folder is identical. A catalog
# change is build.py, then this, the outputs committed together.
#
#   python3 tools/theme_catalog/gen_theme_files.py
import json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
import roles                                                           # noqa: E402

CATALOG = os.path.join(REPO, 'docs', 'themes', 'catalog.json')
OUT = os.path.join(REPO, 'assets', 'themes')
THEME_FILE_H = os.path.join(REPO, 'src', 'gui', 'theme_file.h')
BUILTIN = 'windows-2000-standard'
ROLES_INC = os.path.join(REPO, 'src', 'gui', 'theme_clearlooks_roles.inc')
MEMBERS_INC = os.path.join(REPO, 'src', 'gui', 'theme_clearlooks_members.inc')
GENERATED = '// GENERATED by tools/theme_catalog/gen_theme_files.py; never hand-edit.\n'
SUFFIX = '.theme'

# THE ROLE TABLE'S ORDER (kGuiThemeRoles), checked against the header at every run
ROLE_ORDER = ('ground', 'label', 'hilight', 'light_3d', 'shadow', 'dk_shadow', 'selected_fill', 'selected_text',
              'field_ground', 'field_text', 'clock_ground', 'clock_text', 'card_ground', 'card_text', 'card_frame',
              'caption_active', 'caption_active_gradient', 'caption_active_text', 'caption_inactive',
              'caption_inactive_gradient', 'caption_inactive_text')
# the chrome: theme-file role <- roles.light_roles' name
CHROME = (('ground', 'ground'), ('label', 'label'), ('hilight', 'bevel_hilight'), ('light_3d', 'bevel_light'),
          ('shadow', 'bevel_shadow'), ('dk_shadow', 'bevel_dkshadow'), ('selected_fill', 'selected_fill'),
          ('selected_text', 'selected_text'), ('field_ground', 'field_ground'), ('field_text', 'field_text'),
          ('clock_ground', 'ground'), ('clock_text', 'label'))
# the families whose clock panel is the field pair (the head's rule): clock role <- roles.light_roles' name
CLOCK_FROM_FIELD = {'gnome2': (('clock_ground', 'field_ground'), ('clock_text', 'field_text'))}
# the card: theme-file role <- the catalog role (named only when the entry records both); its frame named alone
CARD = (('card_ground', 'info_ground'), ('card_text', 'info_text'))
CARD_FRAME = ('card_frame', 'info_frame')
# the flat caption's pairs (kGuiThemeCaptionGradients, src/gui/theme_file.h): a file naming a start and not its end
# gets the end equal to the start
CAPTION_GRADIENTS = (('caption_active', 'caption_active_gradient'), ('caption_inactive', 'caption_inactive_gradient'))
ROW = r'\{"([a-z0-9_]+)",\s*&GuiPalette::\w+,\s*0x([0-9A-Fa-f]{6})\}'


def role_table():
    """kGuiThemeRoles read off src/gui/theme_file.h and the Clearlooks block it includes at its end
    (theme_clearlooks_roles.inc, this script's own output) -> ((name, the built-in's '#RRGGBB'), ...) in order."""
    text = open(THEME_FILE_H).read()
    body = text[text.index('kGuiThemeRoles[] = {'):]
    body = body[:body.index('};')]
    rows = re.findall(ROW, body)
    if os.path.exists(ROLES_INC): rows += re.findall(ROW, open(ROLES_INC).read())
    return tuple((n, '#' + v.upper()) for n, v in rows)


def role_table_names():
    """kGuiThemeRoles' hand-written names in order (the Clearlooks block apart)."""
    return tuple(n for n, _ in role_table() if not n.startswith('cl_'))


def clearlooks_tones(entries):
    """The one GNOME 2 entry's engine tones {role: '#RRGGBB'}, in their order."""
    es = [e for e in entries if 'engine_tones' in e]
    if len(es) != 1: raise SystemExit(f'gen_theme_files: {len(es)} catalog entries carry engine tones, not 1')
    return es[0]['engine_tones']


def write_includes(tones):
    """The role table's Clearlooks block and GuiPalette's members, in the tones' order (the head)."""
    roles = (GENERATED + '// THE CLEARLOOKS BLOCK of kGuiThemeRoles (src/gui/theme_file.h, included at the table\'s end):\n'
             '// the Clearlooks painters\' tones, each built-in byte squeeze\'s own (build.py engine_tones).\n' +
             ''.join(f'    {{"{r}", &GuiPalette::{r}, 0x{v[1:].upper()}}},\n' for r, v in tones.items()))
    members = (GENERATED + '// THE CLEARLOOKS BLOCK of GuiPalette (src/gui/render.h, included at the struct\'s end), in\n'
               '// the role table\'s order: the Clearlooks painters\' tones (src/gui/clearlooks_paint.h).\n' +
               ''.join(f'    GuiColor {r};\n' for r in tones))
    for path, text in ((ROLES_INC, roles), (MEMBERS_INC, members)):
        with open(path, 'w', newline='\n') as f: f.write(text)


def file_roles(e):
    """One catalog entry -> {theme-file role: '#RRGGBB'} (the head's rule)."""
    light = roles.light_roles(e)
    out = {role: light[src] for role, src in CHROME}
    out.update({role: light[src] for role, src in CLOCK_FROM_FIELD.get(e['family'], ())})
    out.update(roles.caption_roles(e))
    if all(src in e['roles'] for _, src in CARD):
        out.update({role: e['roles'][src] for role, src in CARD})
    if CARD_FRAME[1] in e['roles']: out[CARD_FRAME[0]] = e['roles'][CARD_FRAME[1]]
    out.update(e.get('engine_tones', {}))
    return out


def resolved_roles(e):
    """One catalog entry -> every role's '#RRGGBB' as the app resolves its theme (theme_file.h's head): the built-in's
    values, overwritten by the roles the entry's file names; the built-in itself, which has no file, its own values.
    Read by crops.py, so a crop paints what the app paints."""
    out = dict(role_table())
    if e['key'] != BUILTIN:
        named = file_roles(e)
        out.update(named)
        for start, end in CAPTION_GRADIENTS:
            if start in named and end not in named: out[end] = named[start]
    return out


def text_of(rs):
    order = tuple(n for n, _ in role_table())
    for role, v in rs.items():
        assert role in order, role
        assert re.fullmatch(r'#[0-9A-Fa-f]{6}', v), (role, v)
    return ''.join(f'{role}={rs[role].upper()}\n' for role in order if role in rs)


def main():
    if sys.argv[1:]: raise SystemExit('usage: python3 tools/theme_catalog/gen_theme_files.py')
    if role_table_names() != ROLE_ORDER:
        raise SystemExit(f'gen_theme_files: {THEME_FILE_H}\'s kGuiThemeRoles is {role_table_names()}, not ROLE_ORDER')
    entries = json.load(open(CATALOG))['entries']
    write_includes(clearlooks_tones(entries))
    if [n for n, _ in role_table() if n.startswith('cl_')] != list(clearlooks_tones(entries)):
        raise SystemExit(f'gen_theme_files: {THEME_FILE_H} does not include {ROLES_INC} at its table\'s end')
    if BUILTIN not in [e['key'] for e in entries]: raise SystemExit(f'gen_theme_files: no {BUILTIN} in the catalog')
    # THE BUILT-IN IS ITS CATALOG ENTRY: the role table's values (kGuiThemeRoles) are the bytes the entry's file would
    # name, the roles it names not taking the table's own values back (card_frame)
    builtin = next(e for e in entries if e['key'] == BUILTIN)
    table = dict(role_table())
    named = file_roles(builtin)
    if {r: table[r] for r in named} != named:
        raise SystemExit(f'gen_theme_files: {THEME_FILE_H}\'s built-in is not {BUILTIN}\'s bytes: '
                         f'{ {r: (table[r], v) for r, v in named.items() if table[r] != v} }')
    os.makedirs(OUT, exist_ok=True)
    want = {}
    for e in entries:
        if e['key'] == BUILTIN: continue
        want[e['key'] + SUFFIX] = text_of(file_roles(e))
    stale = sorted(set(os.listdir(OUT)) - set(want))
    for s in stale: os.remove(os.path.join(OUT, s))
    for name, text in want.items():
        with open(os.path.join(OUT, name), 'w', newline='\n') as f: f.write(text)
    print(f'wrote {os.path.relpath(ROLES_INC, REPO)} and {os.path.relpath(MEMBERS_INC, REPO)}: '
          f'{len(clearlooks_tones(entries))} Clearlooks roles')
    print(f'wrote {os.path.relpath(OUT, REPO)}/: {len(want)} theme files (every catalog entry but {BUILTIN}); '
          f'deleted {len(stale)} stale' + (': ' + ', '.join(stale) if stale else ''))


if __name__ == '__main__':
    main()
