#!/usr/bin/env python3
# tools/theme_catalog/gen_theme_table.py — docs/themes/catalog.json -> src/gui/theme_table.h, THE APP'S THEME TABLE
# (architect 2026-10-03): every catalog entry at the two levels (levels.py, the one module of the level
# arithmetic), eleven roles a level, so the app reads recorded bytes and computes no colour. The header is
# GENERATED AND COMMITTED: a catalog change is this script run again and its output committed beside it; the app's
# build needs no Python. The output is byte-stable — the catalog's order, fixed formatting, no timestamp — so two
# runs write identical bytes (run it twice and cmp).
#
#   python3 tools/theme_catalog/gen_theme_table.py
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import levels                                                          # noqa: E402

OUT = os.path.join(levels.REPO, 'src', 'gui', 'theme_table.h')
FIELDS = ('ground', 'label', 'hilight', 'light_3d', 'shadow', 'dk_shadow', 'emboss_light',
          'selected_fill', 'selected_text', 'field_ground', 'field_text')
assert len(FIELDS) == len(levels.ROLES)


def c_string(s):
    assert s.isascii() and '"' not in s and '\\' not in s, s
    return '"' + s + '"'


def words(roles):
    return ', '.join('0x' + roles[r][1:] for r in levels.ROLES)


def main():
    es = levels.entries()
    L = ['// GENERATED by tools/theme_catalog/gen_theme_table.py from docs/themes/catalog.json; DO NOT EDIT.',
         '// Regenerate after any catalog change and commit the output beside it.',
         '//',
         '// THE THEME TABLE (architect 2026-10-03): every imported desktop theme of the catalog at its two',
         '// LEVELS, light / dark, each a row of 0xRRGGBB words — the recorded bytes, and for dark the level',
         '// arithmetic run once here (tools/theme_catalog/levels.py, its rule stated there), so the app',
         '// does no colour arithmetic. The roles and their mapping onto the painters are render.h\'s palette',
         '// block; the active row is the device config\'s `theme` and `theme_level` (device_config.h).',
         '#pragma once',
         '',
         '#include <cstdint>',
         '',
         '// One level of one theme, in levels.py\'s role order: the ground, the label, Windows\' relief quartet',
         '// (Hilight, 3DLight, Shadow, DkShadow), the emboss\'s light copy, then the selected and field pairs.',
         'struct GuiThemeLevelWords {',
         '    uint32_t ' + ', '.join(FIELDS[:7]) + ';',
         '    uint32_t ' + ', '.join(FIELDS[7:]) + ';',
         '};',
         '',
         '// One catalog entry: its key (what the device config names), its display name and family, and its',
         '// two levels.',
         'struct GuiThemeEntry {',
         '    const char*        key;',
         '    const char*        name;',
         '    const char*        family;',
         '    GuiThemeLevelWords light;',
         '    GuiThemeLevelWords dark;',
         '};',
         '',
         f'inline constexpr int kGuiThemeCount = {len(es)};',
         '',
         'inline constexpr GuiThemeEntry kGuiThemeTable[kGuiThemeCount] = {']
    for e in es:
        L.append(f'    {{{c_string(e["key"])}, {c_string(e["name"])}, {c_string(e["family"])},')
        for i, lvl in enumerate(levels.LEVELS):
            L.append(f'     {{{words(levels.level_roles(e, lvl))}}}{"," if i < len(levels.LEVELS) - 1 else "},"}  // {lvl}')
    L += ['};', '']
    text = '\n'.join(L)
    open(OUT, 'w').write(text)
    print(f'wrote {os.path.relpath(OUT, levels.REPO)}: {len(es)} entries x {len(levels.LEVELS)} levels')


if __name__ == '__main__':
    main()
