#!/usr/bin/env python3
# tools/theme_catalog/gen_cool_edit_presets.py — tools/theme_catalog/cool_edit_presets.txt -> THE BUILT-IN PALETTES'
# GENERATED INCLUDE, src/gui/palette_presets.inc (the rows of kGuiBuiltinPalettes, src/gui/palette_file.h, which owns
# what a palette is and does).
# THE BUILT-IN PALETTES ARE COOL EDIT'S COLOR PRESETS (architect 2026-10-09 ~13:30: "old palettes can be deleted — only
# Cool Edit Pro palettes for waveform needed now"; the program is Cool Edit under every chrome): EVERY scheme Cool Edit
# Pro 2.1 carries in coolpro.exe, in its own order, each a KEY, a DISPLAY NAME and THE TWELVE PROGRAM ROLES
# (kGuiPaletteRoles, read off palette_file.h and checked against ROLE_ORDER). Its first, Cool Edit's "(Default
# Scheme)", is THE DEFAULT PALETTE under every chrome (`cool-edit-default`, palette_file.h's kGuiDefaultPaletteKey).
#
# THE SOURCE (cool_edit_presets.txt's own head says where it came from): the first line is "(Default Scheme)" and its
# values on the same line; after it EVERY values line is followed by its name line (the two the exe's text lacks come
# from Cool Edit's own registry, the file's head). A values line followed by another values line, or by the file's
# end, is the run's hard fail, the first such line named; a name line following no values line likewise. Lines
# opening with '#' are the file's note.
#
# THE TRANSCRIPTION, each role <- the scheme's key, nothing derived but the outline:
#   waveform_canvas <- WvBk          waveform_ink <- WvFg          grid <- GrdL          center <- Cntr
#   cue <- CueM                      range <- RngM                 playhead_stem <- Curs
#   face <- Face, and a scheme recording no Face ("Classic Cool") takes THE DEFAULT SCHEME'S, 626C7B — Cool Edit's own
#     fallback, the panel then wearing the default's face;
#   waveform_outline <- THE INK AT HLS LIGHTNESS 0.3157, hue and saturation kept: Cool Edit records no outline, and the
#     lit outline takes the view bar span's shadow rule (src/gui/cool_edit_derive.h's `span_shadow` tone, its (a, b)
#     read off that file and checked to be (0, 0.3157)), its round trip ported below operation for operation, so the
#     bytes are cool_edit_derive.h's tone() exactly (palette_file.cpp's static_assert proves every row);
#   THE THREE COOL EDIT HAS NO KEY FOR, the same in every preset: invalid_label 800000 and invalid_label_selected FF0000
#     (Windows' dark and bright red of the sixteen, architect 2026-10-09) and scanner FFFFFF (architect 2026-10-07).
#   UNUSED, no role: Bndy (the boundary lines are not drawn), _Sel, ChLi, ChBk, ChGr, ChDt, SpHi, SpLo, SpRv, SpGm,
#     _LED, Edit, UseW, PBSg, prog, STWa, STSp, AnyL, AnyR.
# THE KEY is `cool-edit-` and the display name lowercased, every run of other characters one hyphen ("CEPro 1.2" ->
# `cool-edit-cepro-1-2`), the `palette` device key's word; THE DISPLAY NAME is Cool Edit's own, "Default" for its
# "(Default Scheme)". Keys and display names are checked unique, every key in the catalog key grammar and every
# display name printable ASCII within the palette name grammar's 40 bytes (a typed preset name equal to one is
# refused as taken, color_picker.cpp's commit_name).
#
# BYTE-STABLE: the presets in the file's order, the roles in the table's, uppercase hex, LF, no timestamp; run it twice
# and the include is identical. THE INCLUDE IS ITS OUTPUT, NEVER HAND-EDITED: a change is the text, then this, the
# output committed with it.
#
#   python3 -I tools/theme_catalog/gen_cool_edit_presets.py [path to the presets text]
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))

SOURCE = os.path.join(HERE, 'cool_edit_presets.txt')
PALETTE_FILE_H = os.path.join(REPO, 'src', 'gui', 'palette_file.h')
COOL_EDIT_DERIVE_H = os.path.join(REPO, 'src', 'gui', 'cool_edit_derive.h')
PRESETS_INC = os.path.join(REPO, 'src', 'gui', 'palette_presets.inc')
GENERATED = '// GENERATED by tools/theme_catalog/gen_cool_edit_presets.py; never hand-edit.\n'

# THE ROLE TABLE'S ORDER (kGuiPaletteRoles), checked against the header at every run
ROLE_ORDER = ('waveform_canvas', 'waveform_ink', 'waveform_outline', 'grid', 'center', 'cue', 'range', 'invalid_label',
              'invalid_label_selected', 'playhead_stem', 'scanner', 'face')
# role <- the scheme's key (the head)
FROM_KEY = {'waveform_canvas': 'WvBk', 'waveform_ink': 'WvFg', 'grid': 'GrdL', 'center': 'Cntr', 'cue': 'CueM',
            'range': 'RngM', 'playhead_stem': 'Curs', 'face': 'Face'}
# the roles Cool Edit has no key for (the head)
FIXED = {'invalid_label': 0x800000, 'invalid_label_selected': 0xFF0000, 'scanner': 0xFFFFFF}
DEFAULT_LINE = '(Default Scheme),'
DEFAULT_NAME = 'Default'
DEFAULT_KEY = 'cool-edit-default'
KEY_PREFIX = 'cool-edit-'
OUTLINE = (0.0, 0.3157)   # the span shadow's (a, b), checked against cool_edit_derive.h
TABLE_ROW = r'\{"([a-z_]+)",\s*&GuiPalette::\w+\}'


def role_table():
    """kGuiPaletteRoles' names read off src/gui/palette_file.h, in order."""
    text = open(PALETTE_FILE_H).read()
    body = text[text.index('kGuiPaletteRoles[] = {'):]
    body = body[:body.index('};')]
    return tuple(re.findall(TABLE_ROW, body))


def span_shadow_fit():
    """cool_edit_derive.h's `span_shadow` tone's (a, b)."""
    m = re.search(r'\{"span_shadow",\s*0x[0-9A-Fa-f]{6},\s*([-0-9.]+),\s*([-0-9.]+),', open(COOL_EDIT_DERIVE_H).read())
    if not m: raise SystemExit(f'gen_cool_edit_presets: no span_shadow tone in {COOL_EDIT_DERIVE_H}')
    return float(m.group(1)), float(m.group(2))


# -- THE HLS ROUND TRIP, cool_edit_derive.h's tone() operation for operation (Python's floats are its doubles) --------

def frac(x):
    t = x - float(int(x))
    return t + 1.0 if t < 0.0 else t


def rgb_to_hls(r, g, b):
    maxc = (r if r > b else b) if r > g else (g if g > b else b)
    minc = (r if r < b else b) if r < g else (g if g < b else b)
    sumc = maxc + minc
    rangec = maxc - minc
    l = sumc / 2.0
    if minc == maxc: return 0.0, l, 0.0
    s = rangec / sumc if l <= 0.5 else rangec / (2.0 - maxc - minc)
    rc = (maxc - r) / rangec
    gc = (maxc - g) / rangec
    bc = (maxc - b) / rangec
    if r == maxc:   h = bc - gc
    elif g == maxc: h = 2.0 + rc - bc
    else:           h = 4.0 + gc - rc
    return frac(h / 6.0), l, s


def hls_value(m1, m2, hue):
    hue = frac(hue)
    if hue < 1.0 / 6.0: return m1 + (m2 - m1) * hue * 6.0
    if hue < 0.5:       return m2
    if hue < 2.0 / 3.0: return m1 + (m2 - m1) * (2.0 / 3.0 - hue) * 6.0
    return m1


def byte_of(v):
    n = int(v * 255.0 + 0.5)
    return 0 if n < 0 else (255 if n > 255 else n)


def tone(face, a, b):
    h, fl, s = rgb_to_hls(float((face >> 16) & 0xFF) / 255.0, float((face >> 8) & 0xFF) / 255.0,
                          float(face & 0xFF) / 255.0)
    l = a * fl + b
    l = 0.0 if l < 0.0 else (1.0 if l > 1.0 else l)
    if s == 0.0:
        v = byte_of(l)
        return (v << 16) | (v << 8) | v
    m2 = l * (1.0 + s) if l <= 0.5 else l + s - l * s
    m1 = 2.0 * l - m2
    return (byte_of(hls_value(m1, m2, h + 1.0 / 3.0)) << 16) | (byte_of(hls_value(m1, m2, h)) << 8) | \
        byte_of(hls_value(m1, m2, h - 1.0 / 3.0))


# -- THE SOURCE ---------------------------------------------------------------------------------------------------

def parse_values(line):
    """One values line -> {key: value}."""
    out = {}
    for item in line.split(','):
        k, sep, v = item.partition('=')
        if not sep: raise SystemExit(f'gen_cool_edit_presets: not a key=value item: {item!r}')
        if k in out: raise SystemExit(f'gen_cool_edit_presets: duplicate key {k} in {line!r}')
        out[k] = v
    return out


def presets(path):
    """The source -> [(display name, {key: value})] in the file's order (the head's pairing)."""
    lines = [ln for ln in open(path, newline='\n').read().split('\n') if ln and not ln.startswith('#')]
    if not lines or not lines[0].startswith(DEFAULT_LINE):
        raise SystemExit(f'gen_cool_edit_presets: {path} does not open with {DEFAULT_LINE!r}')
    out = [[DEFAULT_NAME, parse_values(lines[0][len(DEFAULT_LINE):])]]
    pending = None   # the values line still waiting for its name line
    for ln in lines[1:]:
        if '=' in ln:
            if pending is not None:
                raise SystemExit(f'gen_cool_edit_presets: the values line {pending!r} is followed by no name line')
            out.append([None, parse_values(ln)])
            pending = ln
        else:
            if pending is None: raise SystemExit(f'gen_cool_edit_presets: the name line {ln!r} follows no values line')
            out[-1][0] = ln
            pending = None
    if pending is not None:
        raise SystemExit(f'gen_cool_edit_presets: the values line {pending!r} is followed by no name line')
    return [tuple(p) for p in out]


def word(values, key, name):
    v = values.get(key)
    if v is None or not re.fullmatch(r'[0-9A-Fa-f]{6}', v):
        raise SystemExit(f'gen_cool_edit_presets: {name} records no six-digit {key}: {v!r}')
    return int(v, 16)


def preset_words(name, values, default_face):
    """One preset -> its twelve words in ROLE_ORDER (the head's transcription)."""
    w = {}
    for role, key in FROM_KEY.items():
        if role == 'face' and key not in values: w[role] = default_face
        else: w[role] = word(values, key, name)
    w['waveform_outline'] = tone(w['waveform_ink'], *OUTLINE)
    w.update(FIXED)
    return [w[r] for r in ROLE_ORDER]


def preset_key(name):
    return KEY_PREFIX + re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')


def main():
    if len(sys.argv) > 2:
        raise SystemExit('usage: python3 -I tools/theme_catalog/gen_cool_edit_presets.py [presets text]')
    source = sys.argv[1] if len(sys.argv) == 2 else SOURCE
    if role_table() != ROLE_ORDER:
        raise SystemExit(f'gen_cool_edit_presets: {PALETTE_FILE_H}\'s kGuiPaletteRoles is {role_table()}, '
                         'not ROLE_ORDER')
    if span_shadow_fit() != OUTLINE:
        raise SystemExit(f'gen_cool_edit_presets: {COOL_EDIT_DERIVE_H}\'s span_shadow is {span_shadow_fit()}, '
                         f'not {OUTLINE}')
    ps = presets(source)
    default_face = word(ps[0][1], 'Face', DEFAULT_NAME)
    names = [n for n, _ in ps]
    keys = [preset_key(n) for n in names]
    if keys[0] != DEFAULT_KEY: raise SystemExit(f'gen_cool_edit_presets: the default\'s key is {keys[0]}')
    for what, xs in (('key', keys), ('display name', names)):
        dup = sorted({x for x in xs if xs.count(x) > 1})
        if dup: raise SystemExit(f'gen_cool_edit_presets: duplicate preset {what}s: {dup}')
    for k in keys:
        if not re.fullmatch(r'[a-z0-9]+(-[a-z0-9]+)*', k) or len(k) > 40:
            raise SystemExit(f'gen_cool_edit_presets: the key {k!r} is outside the key grammar')
    for n in names:
        if not (0 < len(n) <= 40 and all(0x20 <= ord(c) <= 0x7E for c in n) and n == n.strip() and '/' not in n
                and '"' not in n and '\\' not in n):
            raise SystemExit(f'gen_cool_edit_presets: the display name {n!r} is outside the palette name grammar')
    rows = ''.join(f'    {{"{k}", "{n}", {{{", ".join(f"0x{w:06X}" for w in preset_words(n, v, default_face))}}}}},\n'
                   for k, (n, v) in zip(keys, ps))
    with open(PRESETS_INC, 'w', newline='\n') as f:
        f.write(GENERATED +
                '// THE BUILT-IN PALETTES (src/gui/palette_file.h\'s kGuiBuiltinPalettes, included in its initializer): '
                'Cool Edit\n'
                '// Pro 2.1\'s color presets in its own order (tools/theme_catalog/cool_edit_presets.txt), each its key, '
                'its display\n'
                '// name and the twelve in kGuiPaletteRoles\' order under the generator\'s rules; regenerate, never '
                'hand-edit.\n' + rows)
    print(f'wrote {os.path.relpath(PRESETS_INC, REPO)}: {len(ps)} built-in palettes')


if __name__ == '__main__':
    main()
